import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { JSDOM } from 'jsdom';
import * as domain from '../domain.js';

test('formularios demo: equipo, lectura fuera de rango y cierre; sin guardado remoto',async()=>{
  const html=await readFile(new URL('../index.html',import.meta.url),'utf8');
  const source=(await readFile(new URL('../app.js',import.meta.url),'utf8')).replace(/^import .*;\r?\n/gm,'');
  const dom=new JSDOM(html,{url:'http://localhost:5173',runScripts:'outside-only'});
  const w=dom.window;
  w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
  w.HTMLDialogElement.prototype.close=function(){this.open=false;};
  w.HTMLElement.prototype.scrollIntoView=function(){};
  const api={configured:false,supabase:null,loadData(){throw Error('Unexpected remote access');},insertEquipment(){throw Error('Unexpected remote access');},insertReading(){throw Error('Unexpected remote access');},insertResolution(){throw Error('Unexpected remote access');}};
  const orderingSource=await readFile(new URL('../equipment-order.js',import.meta.url),'utf8');
  const ordering=w.eval(`(${orderingSource.replace('export ', '')})`);
  const reportSource=(await readFile(new URL('../reports.js',import.meta.url),'utf8')).replace(/^import .*;\r?\n/gm,'').replace(/export function /g,'function ');
  const reportFactory=w.eval(`(function(${Object.keys(domain).join(',')}){${reportSource}\nreturn createReports;})`)(...Object.values(domain));
  const parameters=[...Object.keys(domain),...Object.keys(api),'equipmentOrdering','createReports'];
  const dependencies={...domain,...api,equipmentOrdering:ordering,createReports:reportFactory};
  const values=parameters.map(key=>dependencies[key]);
  const run=w.eval(`(async function(${parameters.join(',')}){${source}\n})`);
  try {
    await run(...values);
    const $=id=>w.document.getElementById(id);
    assert.equal($('new-equipment').disabled,true);
    $('demo').click();
    assert.equal(w.document.querySelectorAll('.equipment-card').length,3);
    assert.equal($('incident-count').textContent,'1');
    assert.equal($('report-results').hidden,false);
    assert.equal($('report-values').querySelectorAll('tr').length,1);
    assert.equal($('report-chart').querySelectorAll('.chart-point').length,1);
    $('report-equipment').value='demo-2';
    $('report-equipment').dispatchEvent(new w.Event('change'));
    assert.equal($('report-chart').querySelectorAll('.out-of-range').length,1);
    $('report-chart').querySelector('.chart-point').dispatchEvent(new w.Event('click',{bubbles:true}));
    assert.match($('report-detail').textContent,/8,7/);
    assert.equal($('report-values').querySelectorAll('.selected-report-row').length,1);
    const originalFrom=$('report-from').value,originalTo=$('report-to').value;
    $('report-from').value='2000-01-01';$('report-to').value='2000-01-02';
    $('report-form').dispatchEvent(new w.Event('submit',{cancelable:true}));
    assert.equal($('report-results').hidden,true);
    assert.equal($('report-export').disabled,true);
    assert.equal($('report-values').textContent,'');
    assert.match($('report-status').textContent,/No hay mediciones/);
    $('report-from').value='2000-01-03';
    $('report-from').dispatchEvent(new w.Event('change'));
    assert.match($('report-error').textContent,/posterior/);
    $('report-from').value=originalFrom;$('report-to').value=originalTo;
    $('report-to').dispatchEvent(new w.Event('change'));
    const cardIds=()=>[...$('equipment').children].map(card=>card.dataset.equipmentId);
    const pointer=(target,type,x,y)=>{const event=new w.Event(type,{bubbles:true,cancelable:true});Object.assign(event,{pointerId:1,button:0,clientX:x,clientY:y});target.dispatchEvent(event);};
    const firstHandle=$('equipment').querySelector('.drag-handle');
    w.document.elementFromPoint=()=>$('equipment').lastElementChild;
    pointer(firstHandle,'pointerdown',10,10);
    pointer(firstHandle,'pointermove',100,100);
    assert.equal($('equipment').lastElementChild.classList.contains('drop-after'),true);
    pointer(firstHandle,'pointerup',100,100);
    assert.deepEqual(cardIds(),['demo-2','demo-3','demo-1']);
    assert.deepEqual(JSON.parse(w.localStorage.getItem('termolab-equipment-order:demo')),cardIds());
    $('equipment').lastElementChild.querySelector('.drag-handle').dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}));
    assert.deepEqual(cardIds(),['demo-2','demo-1','demo-3']);
    const beforeCancel=cardIds();
    const cancelHandle=$('equipment').querySelector('.drag-handle');
    pointer(cancelHandle,'pointerdown',10,10);
    pointer(cancelHandle,'pointermove',100,100);
    pointer(cancelHandle,'pointercancel',100,100);
    assert.deepEqual(cardIds(),beforeCancel);
    $('new-equipment').click();
    const equipment=$('equipment-form');
    for(const [key,value] of Object.entries({code:'RF-04',name:'Equipo de prueba',location:'Pruebas',min:'2',max:'8'}))equipment.elements[key].value=value;
    equipment.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
    await new Promise(resolve=>setTimeout(resolve,0));
    assert.equal(w.document.querySelectorAll('.equipment-card').length,4);
    assert.deepEqual(cardIds().slice(0,3),['demo-2','demo-1','demo-3']);
    const option=[...$('reading-equipment').options].find(o=>o.textContent.includes('RF-04'));
    $('new-reading').click();
    $('reading-equipment').value=option.value;
    const reading=$('reading-form');
    reading.elements.temperature.value='9.2';reading.elements.responsible.value='Operador de prueba';
    reading.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
    await new Promise(resolve=>setTimeout(resolve,0));
    assert.equal($('incident-count').textContent,'2');
    assert.match($('history').textContent,/Operador de prueba/);
    $('show-incidents').click();
    assert.equal($('history').querySelectorAll('tr').length,2);
    $('history').querySelector('[data-close]').click();
    const closure=$('resolution-form');closure.elements.action.value='Acción documentada';closure.elements.responsible.value='Supervisor';
    closure.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
    await new Promise(resolve=>setTimeout(resolve,0));
    assert.equal($('incident-count').textContent,'1');
    assert.equal(w.localStorage.getItem('termolab-v1'),null);
    $('demo').click();
    assert.equal(w.document.querySelectorAll('.equipment-card').length,0);
    assert.equal($('report-results').hidden,true);
    assert.equal($('report-chart').innerHTML,'');
    $('demo').click();
    assert.deepEqual(cardIds(),['demo-2','demo-1','demo-3']);
  } finally {w.close();}
});
